/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BackButton: typeof import('./components/BackButton.vue')['default']
    Bookshelf: typeof import('./components/about/Bookshelf.vue')['default']
    ContactButton: typeof import('./components/ContactButton.vue')['default']
    Github: typeof import('./components/icons/Github.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Interests: typeof import('./components/about/Interests.vue')['default']
    JobCard: typeof import('./components/work/JobCard.vue')['default']
    Jobs: typeof import('./components/work/Jobs.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    LinkedIn: typeof import('./components/icons/LinkedIn.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NightSky: typeof import('./components/NightSky.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    Philosophy: typeof import('./components/about/Philosophy.vue')['default']
    Placeholder: typeof import('./components/Placeholder.vue')['default']
    Projects: typeof import('./components/work/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./components/SectionCard.vue')['default']
    SectionTitle: typeof import('./components/SectionTitle.vue')['default']
    Tool: typeof import('./components/icons/Tool.vue')['default']
    Tools: typeof import('./components/about/Tools.vue')['default']
  }
}
